version: '3.1'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: mssql2019
    restart: always
    environment:
      - MSSQL_SA_PASSWORD=P@ssw0rd!!!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - "./data:/var/opt/mssql"